"""Protocol messages and errors for the LLM service."""

from .errors import (
    AuthenticationError,
    ContextLengthExceededError,
    GenerationCancelledError,
    InferenceError,
    LLMError,
    MaxSessionsReachedError,
    QueueCongestionError,
    QueueFullError,
    RateLimitError,
    SessionExistsError,
    SessionNotFoundError,
)
from .messages import (
    CancelMessage,
    ChatMessage,
    ClientMessage,
    EndSessionMessage,
    ErrorCode,
    ErrorMessage,
    GenerationConfig,
    GenerationMetrics,
    MessageDoneMessage,
    MessageType,
    OpenAIChatCompletionChunk,
    OpenAIChatCompletionChunkChoice,
    OpenAIChatCompletionChunkDelta,
    OpenAIChatCompletionChoice,
    OpenAIChatCompletionRequest,
    OpenAIChatCompletionResponse,
    OpenAIChatCompletionUsage,
    OpenAIChatMessage,
    Role,
    SendMessageMessage,
    ServerMessage,
    SessionConfig,
    SessionEndedMessage,
    SessionEndReason,
    SessionMetrics,
    SessionStartedMessage,
    StartSessionMessage,
    TokenMessage,
    UsageInfo,
)

__all__ = [
    # Errors
    "LLMError",
    "SessionExistsError",
    "SessionNotFoundError",
    "MaxSessionsReachedError",
    "QueueFullError",
    "QueueCongestionError",
    "ContextLengthExceededError",
    "GenerationCancelledError",
    "InferenceError",
    "AuthenticationError",
    "RateLimitError",
    # Enums
    "MessageType",
    "ErrorCode",
    "SessionEndReason",
    "Role",
    # Messages
    "ChatMessage",
    "GenerationConfig",
    "SessionConfig",
    "StartSessionMessage",
    "SendMessageMessage",
    "CancelMessage",
    "EndSessionMessage",
    "SessionStartedMessage",
    "TokenMessage",
    "MessageDoneMessage",
    "UsageInfo",
    "GenerationMetrics",
    "ErrorMessage",
    "SessionEndedMessage",
    "SessionMetrics",
    # OpenAI-compatible
    "OpenAIChatMessage",
    "OpenAIChatCompletionRequest",
    "OpenAIChatCompletionChoice",
    "OpenAIChatCompletionUsage",
    "OpenAIChatCompletionResponse",
    "OpenAIChatCompletionChunk",
    "OpenAIChatCompletionChunkChoice",
    "OpenAIChatCompletionChunkDelta",
    # Union types
    "ClientMessage",
    "ServerMessage",
]
