"""Observability module for logging and metrics."""

from .logging import configure_logging
from .metrics import (
    llm_active_requests,
    llm_active_sessions,
    llm_avg_ttft,
    llm_estimated_wait,
    llm_gpu_memory_total,
    llm_gpu_memory_used,
    llm_gpu_temperature,
    llm_gpu_utilization,
    llm_pending_requests,
    llm_prompt_tokens_total,
    llm_queue_wait,
    llm_request_latency,
    llm_requests_rejected,
    llm_requests_total,
    llm_sessions_total,
    llm_slo_violations,
    llm_tokens_generated_total,
    llm_tokens_per_second,
    llm_ttft,
    record_generation_metrics,
    record_request_rejected,
    record_session_ended,
    record_slo_violation,
    update_gpu_metrics,
    update_queue_metrics,
    update_session_metrics,
)

__all__ = [
    "configure_logging",
    # Metrics
    "llm_ttft",
    "llm_tokens_per_second",
    "llm_request_latency",
    "llm_queue_wait",
    "llm_requests_total",
    "llm_tokens_generated_total",
    "llm_prompt_tokens_total",
    "llm_sessions_total",
    "llm_requests_rejected",
    "llm_slo_violations",
    "llm_active_sessions",
    "llm_active_requests",
    "llm_pending_requests",
    "llm_estimated_wait",
    "llm_avg_ttft",
    "llm_gpu_utilization",
    "llm_gpu_memory_used",
    "llm_gpu_memory_total",
    "llm_gpu_temperature",
    # Helper functions
    "record_generation_metrics",
    "record_request_rejected",
    "record_slo_violation",
    "record_session_ended",
    "update_queue_metrics",
    "update_session_metrics",
    "update_gpu_metrics",
]
